Repository citizenfx/fivem, pull requests merged in 2024-09, with the labels that each got.

#2730 Add new valid Epic installation path for gameselect process
  code/client/launcher/GameSelect.cpp
Labels: enhancement, ready-to-merge

#2755 fix(ext/cfx-ui): South Korea system locale
  ext/cfx-ui/src/cfx/apps/mpMenu/services/intl/intl.mpMenu.ts
Labels: enhancement, ready-to-merge

#2756 fix(state/scripting): fixes player natives trying to reference non-existent player entity
  code/components/citizen-server-impl/src/state/PlayerStateScriptFunctions.cpp
Labels: enhancement, ready-to-merge

#2757 fix(native-decls): fix invalid operator in Lua examples
  ext/native-decls/AddStateBagChangeHandler.md
  ext/native-decls/GetEntityFromStateBagName.md
Labels: ready-to-merge, documentation

#2750 fix(onesync): CPlayerGameStateDataNode for b3095
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
Labels: ready-to-merge
