Repository citizenfx/fivem, pull requests merged in 2024-02, with the labels that each got.

#2375 fix(github): PR labeling permission
  .github/workflows/pr_opened.yml
Labels: ready-to-merge

#2370 Add `GET_WORLD_COORD_FROM_SCREEN_COORD` for RedM
  code/components/extra-natives-five/include/GamePrimitives.h
  code/components/extra-natives-five/src/GamePrimitives_Im3D.cpp
  code/components/extra-natives-rdr3/include/GamePrimitives.h
  code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
Labels: ready-to-merge, RedM

#2393 Reset "can stand on top" flag and map after disconnection in FiveM
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
Labels: ready-to-merge

#2396 feat(scripting/v8): allow to set the max listeners count
  data/shared/citizen/scripting/v8/index.d.ts
  data/shared/citizen/scripting/v8/main.js
Labels: ready-to-merge, ScRT: JS
