Repository citizenfx/fivem, pull requests merged in 2024-12, with the labels that each got.

#2973 feat(extra-natives/five): track natives
  code/components/extra-natives-five/src/TrackNatives.cpp
  ext/native-decls/GetTrackBrakingDistance.md
  ext/native-decls/GetTrackMaxSpeed.md
  ext/native-decls/IsTrackEnabled.md
  ext/native-decls/IsTrackSwitchedOff.md
  ext/native-decls/SetTrackBrakingDistance.md
  ext/native-decls/SetTrackEnabled.md
  ext/native-decls/SetTrackMaxSpeed.md
Labels: ready-to-merge, triage

#2851 tweak(codegen): set VAR_STRING as an unsupported type for OAL
  ext/natives/codegen_out_native_lua.lua
Labels: ready-to-merge, RedM

#2972 feat(extra-natives/five): train movement natives
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/GetTrainCruiseSpeed.md
  ext/native-decls/GetTrainDirection.md
  ext/native-decls/GetTrainSpeed.md
  ext/native-decls/GetTrainState.md
  ext/native-decls/SetTrainState.md
Labels: ready-to-merge, triage

#2902 Minor fixes for trains, use `IsEntityValid` for other calls checking if the entity exists
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/DeleteEntity.md
  ext/native-decls/DeleteTrain.md
Labels: ready-to-merge

#2965 fix(game/five): crash when no medium lod exists on a vehicle
  code/components/gta-core-five/src/CrashFixes.DecalCallbacks.cpp
Labels: ready-to-merge

#2966 feat(nui): add `SET_NUI_ZINDEX`
  code/components/nui-resources/src/ResourceUIScripting.cpp
  ext/native-decls/SetNuiZindex.md
  ext/ui-build/data/root.html
Labels: ready-to-merge, RedM

#2991 fix(extra-natives-five): Fix unable to set last pixel of runtime texture
  code/components/extra-natives-five/src/RuntimeAssetNatives.cpp
Labels: ready-to-merge

#3025 fix(scripting): RPC natives pointer args for player type
  ext/natives/codegen_out_pointer_args.lua
Labels: ready-to-merge, triage

#2960 tweak(game/fivem/loadscreen): Initialize the player for RAGE with manual shutdown
  code/components/loading-screens-five/src/LoadingScreens.cpp
Labels: ready-to-merge

#2982 tweak(extra-natives/five): sanitize mission train creation
  code/components/extra-natives-five/include/Train.h
  code/components/extra-natives-five/src/NativeFixes.cpp
  code/components/extra-natives-five/src/TrackNatives.cpp
Labels: invalid, ready-to-merge

#2990 Mumble fixes
  code/components/voip-mumble/include/MumbleClientImpl.h
  code/components/voip-mumble/src/MumbleAudioInput.cpp
  code/components/voip-mumble/src/MumbleAudioOutput.cpp
  code/components/voip-mumble/src/MumbleClient.cpp
  code/components/voip-mumble/src/MumbleClientState_User.cpp
  code/components/voip-mumble/src/MumbleCrypto.cpp
Labels: ready-to-merge, RedM, feature-branch

#3043 fix(state): fix not being able to use any entity native calls in 'entityRemoved'
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
Labels: invalid, ready-to-merge
