Repository citizenfx/fivem, pull requests merged in 2024-03, with the labels that each got.

#2381 Refine net time sync code for OneSync
  code/components/gta-net-five/include/netTimeSync.h
  code/components/gta-net-five/src/CloneExperiments.cpp
  code/components/gta-net-five/src/CloneManager.cpp
  code/components/gta-net-five/src/NetHook.cpp
  code/components/gta-net-five/src/netTimeSync.cpp
  code/components/gta-net-rdr3/component.lua
  code/components/gta-net-rdr3/include/netTimeSync.h
  code/components/gta-net-rdr3/src/CoreNetworking.cpp
Labels: ready-to-merge, RedM, onesync

#2417 fix(steam): support steamclient64.dll 8.75.5.19... for now.
  code/components/steam/src/ClientEngineMapper.cpp
Labels: ready-to-merge

#2400 fix(client): Cleanup various static sig patterns and put them in Hook…
  code/components/extra-natives-five/src/NuiAudioSink.cpp
  code/components/extra-natives-five/src/WeaponExtraNatives.cpp
  code/components/gta-core-five/src/BlockLoadSetters.cpp
  code/components/gta-net-five/src/NetHook.cpp
  code/components/gta-streaming-five/src/LoadStreamingFile.cpp
  code/components/gta-streaming-five/src/PatchPackfileLimit.cpp
  code/components/gta-streaming-five/src/Streaming.cpp
  code/components/rage-device-five/src/fiAssetManager.cpp
  code/components/rage-graphics-five/src/DrawCommands.cpp
  code/components/rage-input-five/src/InputHook.cpp
Labels: ready-to-merge

#2421 Workaround for ped props limit in FiveM
  code/components/gta-core-five/src/PatchPedPropsLimit.cpp
Labels: ready-to-merge

#2423 fix(scripting-mono-v2): allow scheduling from non-main threads
  code/client/clrcore-v2/BaseScript.cs
  code/client/clrcore-v2/Coroutine/Scheduler.cs
  code/client/clrcore-v2/Interop/Types/ScriptSharedData.cs
  code/client/clrcore-v2/ScriptInterface.cs
  code/components/citizen-scripting-mono-v2/include/MonoScriptRuntime.h
  code/components/citizen-scripting-mono-v2/include/ScriptSharedData.h
  code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
Labels: ready-to-merge, ScRT: C#

#2368 tweak(client): remove non-ASLR game executables
  code/client/launcher/premake5.lua
  code/components/sticky/src/LaunchIntercept.cpp
Labels: ready-to-merge, has-dependencies

#2437 tweak(scripting/mono-v2): bump pilot date
  code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
Labels: ready-to-merge, ScRT: C#
