Repository citizenfx/fivem, pull requests merged in 2024-10, with the labels that each got.

#2728 tweak(conhost): use circular_buffer instead of ImVector
  code/components/conhost-v2/src/ConsoleHostGui.cpp
Labels: ready-to-merge

#2733 fix(extra-natives/five): fix crosshair bottom line drawn incorrectly
  code/components/extra-natives-five/src/DrawImNatives.cpp
Labels: ready-to-merge

#2737 fix(clr/shared): remove preprocessor stuff for Object
  code/client/clrcore-v2/Game/Shared/Game.cs
Labels: ready-to-merge

#2738 fix(clr/shared): fix GetGamePool for server
  code/client/clrcore-v2/Game/Shared/Game.cs
  code/client/clrcore/Server/Entity.cs
  code/client/clrcore/Server/Prop.cs
Labels: invalid, ready-to-merge

#2741 feat(server/state): add `[GET/SET]_ENTITY_ORPHAN_MODE`
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetEntityOrphanMode.md
  ext/native-decls/SetEntityOrphanMode.md
Labels: enhancement, ready-to-merge

#2744 fix(voip/mumble): Voice cracking on high load
  code/components/voip-mumble/src/MumbleAudioInput.cpp
  code/components/voip-mumble/src/MumbleAudioOutput.cpp
Labels: ready-to-merge, RedM

#2759 feat(mono): allow for code definitions to be split
  ext/natives/codegen_out_cs.lua
Labels: enhancement, ready-to-merge, ScRT: C#, RedM

#2778 fix(clcore-v2): Fix ReplicateMethodAccessException for Callbacks
  code/client/clrcore-v2/Interop/LocalFunction.cs
Labels: ready-to-merge, ScRT: C#

#2781 tweak(scripting/v8): better error messages for ref calls
  data/shared/citizen/scripting/v8/main.js
Labels: ready-to-merge, triage

#2785 feat(server): add getters for neons
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetVehicleNeonColour.md
  ext/native-decls/GetVehicleNeonEnabled.md
Labels: ready-to-merge

#2797 fix(game/five): verify pickup weapon component is valid on creation
  code/components/gta-core-five/src/CrashFixes.InvalidPickupCreation.cpp
Labels: ready-to-merge

#2803 feat(extra-natives): add `CNetObject` to `GET_GAME_POOL`
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  code/components/extra-natives-five/src/PoolTraversalNatives.cpp
  ext/native-decls/GetGamePool.md
Labels: enhancement, ready-to-merge

#2818 tweak(clrcore): add missing LicensePlateStyle enum types
  code/client/clrcore/External/Vehicle.cs
Labels: invalid, ready-to-merge, ScRT: C#

#2834 fix: vehicle sync tree causing getters to return the wrong values
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
Labels: ready-to-merge

#2875 fix(mono): fix breakage accidentally introduced in #2740
  code/client/clrcore/External/Tasks.cs
Labels: ready-to-merge

#2827 feat(gameinput): new sorting algo and new native
  code/components/citizen-resources-gta/src/GameInputFunctions.cpp
  code/components/gta-core-five/include/GameInput.h
  code/components/gta-core-five/src/GameInput.cpp
  ext/native-decls/SetKeyMappingHideResources.md
Labels: ready-to-merge

#2849 fix(game/five): verify pickup weapon component is valid on creation ( again, but proper )
  code/components/gta-core-five/src/CrashFixes.InvalidPickupCreation.cpp
Labels: ready-to-merge

#2886 tweak(console): Improve keyboard focus
  code/components/conhost-v2/src/ConsoleHostGui.cpp
Labels: ready-to-merge, RedM

#2828 fix(build/linux): WSL build adjustments
  code/tools/ci/wsl-build.sh
Labels: ready-to-merge

#2861 fix(scripting/mono-v2): validate app domain before removing ref
  code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
Labels: ready-to-merge, ScRT: C#

#2883 fix(ext/cfx-ui): afterRender not firing for identity service
  ext/cfx-ui/src/cfx/apps/mpMenu/services/linkedIdentities/linkedIdentities.service.ts
Labels: ready-to-merge

#2893 fix(server/state): properly reassign entities that are set to `EntityOrphanMode::KeepEntity`
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: ready-to-merge
