Repository citizenfx/fivem, pull requests merged in 2024-07, with the labels that each got.

#2609 tweak(scripting/mono-v2): bump pilot date
  code/components/citizen-scripting-mono-v2/src/MonoScriptRuntime.cpp
Labels: bug

#2592 fix(gamestate/server): Populate CGlobalFlagsDataNode on object create
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerSetters.cpp
Labels: ready-to-merge

#2603 feat(data): Increased PoolSizes `ROPE` 12 -> 32 & `ropeData` 8 -> 24
  data/client/citizen/common/data/gameconfig.xml
Labels: ready-to-merge, triage

#2620 fix(game/five): fixes a crash caused by colliding objects without a drawhandler
  code/components/gta-core-five/src/CrashFixes.DrawHandler.cpp
Labels: ready-to-merge, crash

#2624 feat(rdr3): Manifest statement for custom train tracks
  code/components/citizen-resources-gta/src/ResourcesTest.cpp
  code/components/gta-core-rdr3/src/PatchTrainTrackCrashes.cpp
  code/components/gta-core-rdr3/src/PatchTrainTrackFileOverride.cpp
Labels: ready-to-merge, RedM

#2618 fix(system-resources/chat): scroll to bottom and show chat on new message
  ext/system-resources/resources/chat/html/App.ts
Labels: ready-to-merge

#2645 tweak(data/rdr3): Increase netGameEvent, atDNetEventNode pool size and add them in poolEntriesTable
  code/components/gta-core-rdr3/src/PoolManagement.cpp
  data/client_rdr/citizen/common/data/gameconfig.xml
Labels: ready-to-merge, RedM

#2652 fix(game/five): prevent physical attachments from becoming cyclic
  code/components/gta-core-five/src/CrashFixes.PhysicalCyclicAttachment.cpp
Labels: ready-to-merge

#2570 fix(natives/rpc): Keep code fencing in doc summary
  ext/natives/codegen.lua
  ext/natives/codegen_out_markdown.lua
Labels: ready-to-merge

#2662 tweak(rdr3/poolManagement): Add missing pool names in pool entries table
  code/components/gta-core-rdr3/src/PoolManagement.cpp
Labels: ready-to-merge

#2625 feat(net): support dynamic server endpoints using handover
  code/components/net/src/NetLibrary.cpp
Labels: ready-to-merge, triage

#1234 fix(rage-device/five): Error out on cloud files
  code/components/rage-device-five/src/HookInitialMount.cpp
Labels: ready-to-merge
