Repository citizenfx/fivem, pull requests merged in 2024-11, with the labels that each got.

#2896 tweak(cfx/nui): convar filtering logic with shouldVarBeShown helper + add `sv_replaceExeToSwitchBuilds`
  ext/cfx-ui/src/cfx/common/services/servers/transformers.ts
Labels: ready-to-merge, triage

#2897 fix(voip-mumble): nullptr check
  code/components/voip-mumble/src/MumbleAudioInput.cpp
Labels: ready-to-merge

#2905 fix(server): don't invoke cfx_internal:serverPrint on empty string
  code/components/citizen-server-impl/src/packethandlers/ServerCommandPacketHandler.cpp
Labels: ready-to-merge

#2908 feat(console): rework (selectable/copyable log text entries)
  code/components/conhost-server/component.lua
  code/components/conhost-v2/component.lua
  code/components/conhost-v2/include/Textselect.hpp
  code/components/conhost-v2/src/ConsoleHostGui.cpp
  code/components/conhost-v2/src/ConsoleHostImpl.cpp
  code/components/conhost-v2/src/DrawFPS.cpp
  code/components/conhost-v2/src/Textselect.cpp
Labels: ready-to-merge

#2911 fix(net/five): correct train track node on ownership change
  code/components/gta-net-five/include/netBlender.h
  code/components/gta-net-five/src/CloneObjectManager.cpp
Labels: invalid, ready-to-merge

#2915 tweak(legacy-net/resources): check for gameinit on server-command
  code/components/citizen-legacy-net-resources/src/ResourceNetBindings.cpp
Labels: ready-to-merge

#2917 fix(game/five): cNetObjPhys vtable index for 3258
  code/components/gta-streaming-five/src/GameEventHooks.cpp
Labels: invalid, ready-to-merge

#2898 tweak(compiler/linux): build portability
  code/components/net-base/include/Net.h
  code/server/launcher/src/Main.cpp
Labels: ready-to-merge

#2916 feat(extra-natives/five): train station natives
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/DoesTrainStopAtStations.md
  ext/native-decls/SetTrainStopAtStations.md
Labels: invalid, ready-to-merge

#2948 tweak(docs/natives/GetPlayerIdentifierByType): Add link to known identifiers
  ext/native-decls/GetPlayerIdentifierByType.md
Labels: ready-to-merge

#2949 feat(docs/natives/GetPlayerIdentifier): Improve simple doc
  ext/native-decls/GetPlayerIdentifier.md
Labels: ready-to-merge

#2953 tweak(conhost-v2): switch CPU utilization tracking to dynamic scaling
  code/components/conhost-v2/src/DrawPerf.cpp
Labels: ready-to-merge

#2961 fix(game/five): check for vehicle type on drawhandler shader access
  code/components/gta-core-five/src/CrashFixes.FakeParachuteProp.cpp
Labels: ready-to-merge
