Repository citizenfx/fivem, pull requests merged in 2024-05, with the labels that each got.

#2409 feat(extra-natives/five): GET_VEHICLE_GEAR_RATIO and SET_VEHICLE_GEAR_RATIO
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/GetVehicleGearRatio.md
  ext/native-decls/SetVehicleGearRatio.md
Labels: ready-to-merge

#2427 fix(scripting/lua): Fix not closing to-be-closed variables on error
  code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
Labels: ready-to-merge, triage, ScRT: Lua

#2481 feat(scripting/lua): redm oal natives
  code/components/citizen-scripting-lua/src/LuaScriptNatives.cpp
Labels: ready-to-merge, ScRT: Lua, RedM

#2550 tweak(natives/rpc): Use client-native names and apply aliases
  ext/natives/codegen.lua
Labels: ready-to-merge

#2555 Better gamer tag crew component fix for b3095
  code/components/citizen-playernames-five/src/HookGamerInfo.cpp
Labels: ready-to-merge

#2564 Clamp marker type index in FiveM
  code/components/extra-natives-five/src/NativeFixes.cpp
Labels: ready-to-merge

#2321 fix(tool/formats): five -> rdr3 embedded textures crash on unload
  code/components/rage-formats-x/include/convert/gtaDrawable_five_rdr3.h
  code/components/rage-formats-x/include/convert/phBound_five_rdr3.h
  code/components/rage-formats-x/include/rmcDrawable.h
Labels: ready-to-merge
