Repository citizenfx/fivem, pull requests merged in 2024-04, with the labels that each got.

#2446 Don't mention gameconfig in pool errors in RedM
  code/components/gta-core-rdr3/src/PoolManagement.cpp
Labels: ready-to-merge, RedM

#2452 fix(ext/cfx-ui): added exception for sv_disableClientReplays
  ext/cfx-ui/src/cfx/common/services/servers/transformers.ts
Labels: ready-to-merge

#2480 fix(ext/cfx-ui): updated dependencies
  ext/cfx-ui/package.json
  ext/cfx-ui/yarn.lock
Labels: ready-to-merge

#2463 feat(mono-rt2): add NuiEvent attribute
  code/client/clrcore-v2/Attributes.cs
  code/client/clrcore-v2/BaseScript.cs
  code/client/clrcore-v2/Native/Native.cs
Labels: ready-to-merge, ScRT: C#

#2464 fix(mono-v2): disallow KeyMap to be used on RedM
  code/client/clrcore-v2/Attributes.cs
  code/client/clrcore-v2/BaseScript.cs
Labels: ready-to-merge, ScRT: C#
