Repository citizenfx/fivem, pull requests merged in 2024-08, with the labels that each got.

#2679 fix(clcore): Adjust "==" and "!=" operators to fix null reference exceptions
  code/client/clrcore/External/Game.cs
  code/client/clrcore/External/Model.cs
  code/client/clrcore/External/RelationshipGroup.cs
  code/client/clrcore/External/WeaponAsset.cs
  code/client/clrcore/Math/Matrix.cs
  code/client/clrcore/Math/Matrix3x3.cs
  code/client/clrcore/Math/Quaternion.cs
  code/client/clrcore/Math/Vector2.cs
  code/client/clrcore/Math/Vector3.cs
  code/client/clrcore/Math/Vector4.cs
Labels: ready-to-merge, ScRT: C#, RedM

#1423 feat(server): add steam_webApiDomain convar
  code/components/citizen-server-impl/src/SteamIdentityProvider.cpp
Labels: ready-to-merge

#2194 fix(scripting/v8): raw event listeners
  data/shared/citizen/scripting/v8/main.js
Labels: ready-to-merge, ScRT: JS

#2314 feat(net/client): Add state bag methods
  code/components/citizen-resources-core/include/StateBagComponent.h
  code/components/citizen-resources-core/src/StateBagComponent.cpp
  code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
  ext/native-decls/GetStateBagKeys.md
  ext/native-decls/StateBagHasKey.md
Labels: ready-to-merge

#2462 feat(mono-v2): Enable mono v2 on RedM
  data/client_rdr/components.json
Labels: ready-to-merge, ScRT: C#, RedM

#2488 feat(mono/redm): initial works for rdr
  code/client/clrcore-v2/Client/RedM/AssemblyInfo.cs
  code/client/clrcore-v2/Client/RedM/Entity.cs
  code/client/clrcore-v2/Client/RedM/Game.cs
  code/client/clrcore-v2/Client/RedM/Model.cs
  code/client/clrcore-v2/Client/RedM/Ped.cs
  code/client/clrcore-v2/Client/RedM/Pickup.cs
  code/client/clrcore-v2/Client/RedM/Player.cs
  code/client/clrcore-v2/Client/RedM/Prop.cs
  code/client/clrcore-v2/Client/RedM/Vehicle.cs
  code/client/clrcore-v2/Client/RedM/World.cs
  code/client/clrcore-v2/Game/Shared/Game.cs
  code/client/clrcore-v2/Game/Shared/Interfaces.cs
  code/client/clrcore-v2/Shared/IEntity.cs
  code/client/clrcore/External/Game.cs
  code/premake5.lua
Labels: ready-to-merge, RedM

#2511 Reorganize KVP natives and fix Lua example for the "find" functions
  ext/native-decls/kvp/DeleteResourceKvp.md
  ext/native-decls/kvp/DeleteResourceKvpNoSync.md
  ext/native-decls/kvp/EndFindKvp.md
  ext/native-decls/kvp/FindKvp.md
  ext/native-decls/kvp/FlushResourceKvp.md
  ext/native-decls/kvp/GetResourceKvpFloat.md
  ext/native-decls/kvp/GetResourceKvpInt.md
  ext/native-decls/kvp/GetResourceKvpString.md
  ext/native-decls/kvp/SetResourceKvp.md
  ext/native-decls/kvp/SetResourceKvpFloat.md
  ext/native-decls/kvp/SetResourceKvpFloatNoSync.md
  ext/native-decls/kvp/SetResourceKvpInt.md
  ext/native-decls/kvp/SetResourceKvpIntNoSync.md
  ext/native-decls/kvp/SetResourceKvpNoSync.md
  ext/native-decls/kvp/StartFindKvp.md
  ext/native-decls/kvp/external/StartFindExternalKvp.md
Labels: ready-to-merge

#2544 feat(extra-natives/five): support for cl_crosshair_t command
  code/components/conhost-v2/include/ProductionWhitelist.h
  code/components/extra-natives-five/src/DrawImNatives.cpp
Labels: ready-to-merge

#2627 feat(netsync): serialize CPedAttachDataNode
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
Labels: ready-to-merge

#2628 feat(netsync): serialize CVehicleCreationDataNode
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerSetters.cpp
Labels: ready-to-merge

#2631 Improve Lua error handling
  code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
  data/shared/citizen/scripting/lua/scheduler.lua
Labels: ready-to-merge

#2682 feat(voip/mumble): Add MUMBLE_DOES_CHANNEL_EXIST native
  code/components/gta-net-five/src/MumbleVoice.cpp
  code/components/voip-mumble/include/MumbleClient.h
  code/components/voip-mumble/include/MumbleClientImpl.h
  code/components/voip-mumble/src/MumbleClient.cpp
  code/components/voip-mumble/src/MumbleClientState_Channel.cpp
  ext/native-decls/MumbleDoesChannelExist.md
Labels: ready-to-merge

#2695 feat(data): Add fwPortalSceneGraphNode pool to gameconfig
  data/client/citizen/common/data/gameconfig.xml
Labels: ready-to-merge

#2697 feat(onesync/natives): add GetVehicleHornType
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetVehicleHornType.md
Labels: ready-to-merge

#2721 feat(onesync/helicopters): serialize helicopters datanodes
  code/components/citizen-server-impl/include/ScriptDeprecations.h
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/CanHeliTailBoomBreak.md
  ext/native-decls/GetHeliBodyHealth.md
  ext/native-decls/GetHeliDisableExplodeFromBodyDamage.md
  ext/native-decls/GetHeliEngineHealth.md
  ext/native-decls/GetHeliGasTankHealth.md
  ext/native-decls/GetHeliMainRotorDamageScale.md
  ext/native-decls/GetHeliPitchControl.md
  ext/native-decls/GetHeliRearRotorDamageScale.md
  ext/native-decls/GetHeliRearRotorHealth.md
  ext/native-decls/GetHeliRollControl.md
  ext/native-decls/GetHeliTailRotorDamageScale.md
  ext/native-decls/GetHeliTailRotorHealth.md
  ext/native-decls/GetHeliThrottleControl.md
  ext/native-decls/GetHeliYawControl.md
  ext/native-decls/GetIsHeliEngineRunning.md
  ext/native-decls/GetThrusterSideRcsThrottle.md
  ext/native-decls/GetThrusterThrottle.md
  ext/native-decls/IsHeliTailBoomBroken.md
Labels: ready-to-merge

#2731 tweak(mono-rt2): swap back to using Prop instead of Object
  code/client/clrcore-v2/Client/FiveM/Object.cs
  code/client/clrcore/External/Entity.cs
  code/client/clrcore/External/Prop.cs
  code/client/clrcore/External/WeaponCollection.cs
  code/client/clrcore/External/World.cs
Labels: ready-to-merge, triage

#2739 feat(scripting/state): add `GET_GAME_POOL` server side parity
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetGamePool.md
Labels: ready-to-merge
