Repository citizenfx/fivem, pull requests merged in 2024-06, with the labels that each got.

#2141 feat(net): attribute proper packet names for timeout
  code/components/citizen-server-gui/src/PlayerList.cpp
  code/components/citizen-server-impl/include/GameServerNet.h
  code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
  code/components/debug-net/src/NetDebug.cpp
  code/shared/net/PacketNames.h
Labels: ready-to-merge, triage

#2371 feat(extra-natives/five): Add `SET_INTERIOR_PROBE_LENGTH` for FiveM
  code/components/extra-natives-five/src/InteriorExtraNatives.cpp
  ext/native-decls/SetEmitterProbeLength.md
  ext/native-decls/SetInteriorProbeLength.md
Labels: invalid, ready-to-merge

#2377 tweak(citizen-scripting-v8): increase heap size per isolate to match physical memory size
  code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
Labels: ready-to-merge, ScRT: JS

#2556 tweak(gamestate/server): allow blocking of ScriptEntityStateChangeEvent
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: ready-to-merge, triage

#2579 Workaround for ped component expression mods limit in FiveM
  code/components/gta-core-five/src/PatchPedCompExpressionsLimit.cpp
Labels: ready-to-merge

#2568 tweak(data/rdr3): increase pools size
  data/client_rdr/citizen/common/data/gameconfig.xml
Labels: ready-to-merge, RedM
