Repository citizenfx/fivem, pull requests merged in 2025-04, with the labels that each got.

#3001 tweak(server): ignore resources that have a name starting with '.' in resource scan
  code/components/citizen-server-impl/src/ServerResourceList.cpp
Labels: ready-to-merge

#3291 Add documentation to ExecuteCommand native
  ext/native-decls/ExecuteCommand.md
Labels: ready-to-merge

#3302 fix(core-five): tmp disable expanded blip categories on builds <= 2189
  code/components/gta-core-five/src/PatchBlipCategories.cpp
Labels: ready-to-merge

#3304 fix(extra-natives-five): process fuel only when engine is on
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
Labels: ready-to-merge, triage

#2877 tweak(gameserver): Don't enforce sessionmanager with OneSync
  code/components/citizen-server-impl/src/GameServer.cpp
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: ready-to-merge, triage

#3283 feat(extra-natives-rdr3): add `GET_ENTITIES_IN_RADIUS` for RedM
  code/components/citizen-scripting-core/include/ScriptSerialization.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  code/components/extra-natives-rdr3/src/EntityNatives.cpp
  code/components/gta-streaming-rdr3/include/EntitySystem.h
  ext/native-decls/GetEntitiesInRadius.md
Labels: ready-to-merge, RedM

#3295 tweak(gta-core-five): set game_useSynchronousAudio convar default true
  code/components/gta-core-five/src/GameAudioState.cpp
Labels: ready-to-merge

#3299 fix(imgui): various improvements
  code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
  code/components/citizen-server-gui/src/PlayerList.cpp
  code/components/conhost-v2/src/ConsoleHostGui.cpp
  code/components/conhost-v2/src/ConsoleHostImpl.cpp
  code/components/conhost-v2/src/DrawPerf.cpp
  code/components/gta-net-five/src/CloneDebug.cpp
Labels: ready-to-merge

#3300 tweak(conhost-v2): clamp CPU usage to 100%
  code/components/conhost-v2/src/DrawPerf.cpp
Labels: ready-to-merge

#3318 fix(core/rdr3): block custom startup.meta file
  code/components/gta-core-rdr3/src/GameInitRage.cpp
Labels: ready-to-merge, RedM

#3327 tweak(client/launcher): Gen9-specific warnings
  code/client/launcher/GameSelect.cpp
Labels: ready-to-merge, triage

#3330 fix(client/mumble): request resync if we fail to decrypt a packet after 1 seconds
  code/components/voip-mumble/include/MumbleClientImpl.h
  code/components/voip-mumble/src/MumbleClient.cpp
  code/components/voip-mumble/src/MumbleCrypto.cpp
Labels: ready-to-merge

#3340 fix(legitimacy/rdr3): add mojo as a dependency
  code/components/legitimacy/component.json
Labels: ready-to-merge, triage, RedM

#3249 feat(gamestate/server): sv_protectServerEntities
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
  code/components/gta-net-five/src/ClientRPC.cpp
  code/components/gta-net-five/src/CloneManager.cpp
  code/components/gta-net-five/src/NetServerObject.cpp
Labels: ready-to-merge

#3296 feat(core/rdr3): increase texture override pool size
  code/components/gta-streaming-rdr3/src/PatchTextureOverride.cpp
  ext/native-decls/DoesTextureExist.md
  ext/native-decls/RemoveTexture.md
Labels: ready-to-merge, triage, RedM

#3344 fix(core/rdr3): revert serialize component changes
  code/components/gta-streaming-rdr3/src/PatchTextureOverride.cpp
Labels: ready-to-merge, triage, RedM

#3337 feat(rdr3): loading screen support
  code/components/config.lua
  code/components/conhost-v2/src/ConsoleHostGui.cpp
  code/components/gta-net-rdr3/include/HostSystem.h
  code/components/gta-net-rdr3/src/CoreNetworking.cpp
  code/components/loading-screens-five/src/HookLoadingScreens.cpp
  code/components/loading-screens-five/src/LoadingScreens.cpp
  code/components/loading-screens-rdr3/component.json
  code/components/loading-screens-rdr3/component.lua
  code/components/loading-screens-rdr3/component.rc
  code/components/loading-screens-rdr3/include/Local.h
  code/components/loading-screens-rdr3/src/Component.cpp
  data/client_rdr/citizen/load_profile.json
  data/client_rdr/components.json
Labels: ready-to-merge, triage, RedM

#3341 fix(github): bump Linux runner Ubuntu version
  .github/workflows/ci_build.yml
Labels: ready-to-merge

#3349 fix(gta-core-five): invalid bounding volume hierarchy
  code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp
Labels: ready-to-merge, triage

#3351 feat(extra-natives/five): GET_TRAIN_TRACK_INDEX
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/GetTrainTrackIndex.md
Labels: ready-to-merge, triage

#3352 feat(citizen-server): add event listeners for routing bucket changes
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
Labels: ready-to-merge

#3353 tweak(native-decls): update documentation for trains
  ext/native-decls/SetEntityOrphanMode.md
Labels: ready-to-merge, triage
