Repository citizenfx/fivem, pull requests merged in 2025-01, with the labels that each got.

#3014 feat(clcore): Allow iteration of WeaponCollection
  code/client/clrcore/External/WeaponCollection.cs
Labels: ready-to-merge, ScRT: C#

#3000 tweak(extra-natives/five): implement [GET/SET]_VEHICLE_XMAS_SNOW_FACTOR
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/GetVehicleXmasSnowFactor.md
  ext/native-decls/SetVehicleXmasSnowFactor.md
Labels: ready-to-merge, ScRT: C#, ScRT: Lua, ScRT: JS

#3004 fix(clcore): Update WeaponHash.cs with hashes from dlcs mpheist3 to mp2024_01 (latest)
  code/client/clrcore/External/WeaponHash.cs
Labels: ready-to-merge, ScRT: C#

#3052 tweak(mumble): swap to completely using TCP ping for checking if UDP is available
  code/components/voip-mumble/include/MumbleClientImpl.h
  code/components/voip-mumble/src/MumbleClient.cpp
Labels: ready-to-merge, RedM

#3056 fix(commerce): allow the server to refresh sku's after initial load
  code/components/citizen-server-impl/src/ServerExtCommerce.cpp
  ext/native-decls/LoadPlayerCommerceDataExt.md
Labels: ready-to-merge

#2923 fix(gamestate/server): add array bounds checks and fix native decl.
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetVehicleDoorStatus.md
Labels: ready-to-merge

#3063 fix(server/gamestate): memory leak
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
  code/components/citizen-server-impl/src/state/ServerSetters.cpp
  ext/native-decls/server/CreateVehicleServerSetter.md
Labels: ready-to-merge

#2907 feat(core/five): sanitization for attachments on remote peds
  code/components/gta-core-five/component.json
  code/components/gta-core-five/src/PatchAttachCD2545.cpp
  ext/native-decls/OnesyncEnableRemoteAttachmentSanitization.md
Labels: invalid, ready-to-merge

#2987 tweak(ext/cfx-ui): allow automated accounts for servers feeds
  ext/cfx-ui/src/cfx/common/services/activity/ActiveActivityPubFeed.ts
Labels: ready-to-merge

#3050 tweak(fxdk): Change Keymaster to Portal
  ext/sdk/resources/sdk-root/shell/src/fxdk/project/node/project-builder.ts
Labels: ready-to-merge, FxDK, triage

#3060 feat(game/five): add ped prop collection natives
  code/components/extra-natives-five/src/PedCollectionsNatives.cpp
  ext/native-decls/GetPedPropCollectionLocalIndex.md
  ext/native-decls/GetPedPropCollectionName.md
Labels: invalid, ready-to-merge
