Repository citizenfx/fivem, pull requests merged in 2025-05, with the labels that each got.

#3316 feat(kvp-client): add client asynchronous kvp natives
  code/components/citizen-resources-client/src/KVScriptFunctions.cpp
  ext/native-decls/kvp/DeleteResourceKvpNoSync.md
  ext/native-decls/kvp/SetResourceKvpFloatNoSync.md
  ext/native-decls/kvp/SetResourceKvpIntNoSync.md
  ext/native-decls/kvp/SetResourceKvpNoSync.md
Labels: ready-to-merge, triage

#3331 Fixes oversights in original RawKeymap PR
  code/components/extra-natives-five/src/InputNatives.cpp
  data/shared/citizen/scripting/v8/main.js
  ext/native-decls/RegisterRawKeymap.md
  ext/natives/codegen_out_js.lua
Labels: ready-to-merge, triage, RedM

#3356 feat(extra-natives/five): GET_WEAPON_ACCURACY_SPREAD & SET_WEAPON_ACC…
  code/components/extra-natives-five/src/WeaponExtraNatives.cpp
  ext/native-decls/GetWeaponAccuracySpread.md
  ext/native-decls/SetWeaponAccuracySpread.md
Labels: ready-to-merge, triage

#3359 feat(conhost): allow console vertical resizing
  code/components/conhost-v2/src/ConsoleHostGui.cpp
Labels: ready-to-merge

#3361 fix(core-rdr3): fix crash when Blip limit is reached RedM
  code/components/gta-core-rdr3/src/PatchBlipLimitCrash.cpp
Labels: ready-to-merge, triage, RedM

#3362 fix(net/rdr3): Deadlock in CProcessControlUpdateGraph
  code/components/gta-net-five/src/CloneExperiments.cpp
Labels: ready-to-merge, triage, RedM

#3370 fix(server-routing-bucket): change entity argument type
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
Labels: ready-to-merge, triage

#3373 fix(client): vulkan load order
  code/client/launcher/Main.cpp
Labels: ready-to-merge, triage, RedM

#3387 fix(net/five): factory nullptr check
  code/components/gta-net-five/src/NetServerObject.cpp
Labels: ready-to-merge, triage

#2983 feat(gamestate/server): train sync node getters
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/DoesTrainStopAtStations.md
  ext/native-decls/GetTrainBackwardCarriage.md
  ext/native-decls/GetTrainCruiseSpeed.md
  ext/native-decls/GetTrainDirection.md
  ext/native-decls/GetTrainForwardCarriage.md
  ext/native-decls/GetTrainState.md
  ext/native-decls/GetTrainTrackIndex.md
  ext/native-decls/IsTrainCaboose.md
Labels: invalid, ready-to-merge

#3196 feat(five/streaming): expand train track array
  code/components/extra-natives-five/include/Train.h
  code/components/extra-natives-five/src/TrackNatives.cpp
  code/components/gta-streaming-five/src/PatchTrackLimits.cpp
Labels: ready-to-merge

#3285 feat(extra-natives-rdr3): add `GET_ASPECT_RATIO` native RedM
  code/components/extra-natives-rdr3/src/GraphicsNatives.cpp
  ext/native-decls/GetAspectRatio.md
Labels: ready-to-merge, triage, RedM

#3293 fix(core/sbag): make sure our value isn't being erased before we try …
  code/components/citizen-resources-core/src/StateBagComponent.cpp
Labels: ready-to-merge, triage, RedM

#3365 feat(extra-natives/five): add support for configurable outline render technique
  code/components/extra-natives-five/src/GamePrimitives_Outlines.cpp
  ext/native-decls/sdk/ResetEntityDrawOutlineRenderTechnique.md
  ext/native-decls/sdk/SetEntityDrawOutlineRenderTechnique.md
Labels: ready-to-merge, FxDK, triage, needs manual verification

#3386 feat(extra-natives-five): add `SET_WET_CLOTH_PIN_RADIUS_SCALE` for wet cloth physics control
  code/components/extra-natives-five/src/PedExtraNatives.cpp
  ext/native-decls/SetWetClothPinRadiusScale.md
Labels: ready-to-merge, triage

#3392 feat(core/five): patch script ptfx limits
  code/components/gta-core-five/PtfxScriptLimit.cpp
Labels: ready-to-merge, triage

#3393 feat(rdr3): loading screen support
  code/components/config.lua
  code/components/conhost-v2/src/ConsoleHostGui.cpp
  code/components/gta-net-rdr3/include/HostSystem.h
  code/components/gta-net-rdr3/src/CoreNetworking.cpp
  code/components/loading-screens-five/src/HookLoadingScreens.cpp
  code/components/loading-screens-five/src/LoadingScreens.cpp
  code/components/loading-screens-rdr3/component.json
  code/components/loading-screens-rdr3/component.lua
  code/components/loading-screens-rdr3/component.rc
  code/components/loading-screens-rdr3/include/Local.h
  code/components/loading-screens-rdr3/src/Component.cpp
  data/client_rdr/citizen/load_profile.json
  data/client_rdr/components.json
Labels: ready-to-merge, RedM

#3402 feat(graphics/rdr3): add crashometry for vulkan
  code/components/glue/src/GtaNui.cpp
  code/components/rage-graphics-rdr3/include/VulkanHelper.h
  code/components/rage-graphics-rdr3/src/RenderHooks.cpp
Labels: ready-to-merge, triage, RedM

#3406 fix(citizen-scripting-v8): Crash when formatting an exception stack trace from a callback that's inside an eval() function.
  code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
Labels: ready-to-merge, RedM, ScRT: JS
