Repository citizenfx/fivem, pull requests merged in 2025-08, with the labels that each got.

#3524 fix(net-event-doc): fix typedoc not recognizing int
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
Labels: ready-to-merge, triage

#3543 feat(gta-streaming-rdr3): allow registration of custom fonts
  code/components/citizen-resources-gta/src/TextChangingFunctions.cpp
  code/components/gta-streaming-five/src/StreamingFreeTests.cpp
  code/components/gta-streaming-five/src/sfFontStuff.cpp
  code/components/gta-streaming-rdr3/component.lua
Labels: ready-to-merge, triage, RedM

#3544 fix(extra-natives-five): avoid weapon change with no swap enabled
  code/components/extra-natives-five/src/WeaponExtraNatives.cpp
Labels: ready-to-merge, triage

#3547 fix(core/rdr3): crash when targetting invalid ped/player
  code/components/gta-core-rdr3/src/PatchWeaponTargetCrash.cpp
Labels: ready-to-merge, triage, RedM

#3548 fix(gta-core-five): validate river entity archetype
  code/components/gta-core-five/src/CrashFixes.RiverEntities.cpp
Labels: ready-to-merge, triage

#3550 fix(net/rdr3): verify net object model archetype
  code/components/gta-net-rdr3/src/netSyncTree.cpp
Labels: ready-to-merge, triage, RedM

#3565 fix(gta-core-five): overriding ladder registers causing bad collision checks
  code/components/gta-core-five/src/CrashFixes.Ladder.cpp
Labels: ready-to-merge, triage

#3570 feat(gta-core-rdr3): support for increased networked object pool
  code/components/gta-core-rdr3/src/PatchIncreaseMaxObjects.cpp
  code/components/gta-core-rdr3/src/PoolManagement.cpp
Labels: ready-to-merge, triage, RedM

#3571 fix(citizen-devtools): improve search filter of pool list
  code/components/citizen-devtools/src/ResourceTimeWarnings.cpp
Labels: ready-to-merge, triage, RedM

#3573 fix(streaming/rdr3): don't attempt to reload collisions
  code/components/gta-streaming-five/src/LoadStreamingFile.cpp
Labels: ready-to-merge, triage, RedM

#2952 fix(game/five): updateBusySpinner thread constraint check
  code/components/loading-screens-five/src/HookLoadingScreens.cpp
  code/components/rage-input-five/src/InputHook.cpp
  code/components/rage-nutsnbolts-five/include/nutsnbolts.h
  code/components/rage-nutsnbolts-five/src/FrameHook.cpp
Labels: ready-to-merge

#3520 feat(input/rdr3): backport fives input hook improvements
  code/components/rage-input-rdr3/include/InputHook.h
  code/components/rage-input-rdr3/src/InputHook.cpp
Labels: ready-to-merge, triage, RedM

#3551 tweak(server-impl/sbag): reduce the amount of locking for adding routing targets
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: ready-to-merge, triage

#3578 fix(core/rdr3): followup for combat crash
  code/components/gta-core-rdr3/src/PatchWeaponTargetCrash.cpp
Labels: ready-to-merge, triage, RedM

#3580 feat(gta-core-rdr3): support for increased networked vehicle pool
  code/components/gta-core-rdr3/src/PatchIncreaseMaxVehicles.cpp
  code/components/gta-core-rdr3/src/PoolManagement.cpp
Labels: ready-to-merge, RedM

#3598 fix(ext/native): remove gta5 game field for font natives
  ext/native-decls/RegisterFontFile.md
  ext/native-decls/RegisterFontId.md
Labels: ready-to-merge, RedM

#3599 tweak(server): remove warning about the identifiers change
  code/components/citizen-server-main/src/ServerInstance.cpp
Labels: ready-to-merge
