Repository citizenfx/fivem, pull requests merged in 2025-02, with the labels that each got.

#3012 feat: allow resources to retrieve the invoking resource of commands
  code/client/citicore/console/Console.CommandHelpers.h
  code/client/citicore/console/Console.Commands.cpp
  code/client/citicore/console/Console.Commands.h
  code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
  ext/native-decls/GetRegisteredCommands.md
  ext/native-decls/GetResourceCommands.md
Labels: enhancement, invalid, ready-to-merge, RedM

#3061 feat(gamestate/server): ped AI node getter
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/include/state/SyncTrees_Five.h
  code/components/citizen-server-impl/include/state/SyncTrees_RDR3.h
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetPedRelationshipGroupHash.md
Labels: invalid, ready-to-merge

#3068 feat(server/gamestate): freecam status natives
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetPlayerFocusPos.md
  ext/native-decls/IsPlayerInFreeCamMode.md
Labels: ready-to-merge, RedM

#3088 fix(game/five): SET_HELI_*_ROTOR_HEALTH sync fixes
  code/components/extra-natives-five/src/NativeFixes.cpp
Labels: invalid, ready-to-merge

#3089 fix(extra-natives/five): xmas snow grip factor natives
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/SetVehicleXmasSnowFactor.md
Labels: invalid, ready-to-merge

#3096 feat(server/state): add GIVE_PED_SCRIPTED_TASK handler
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: invalid, ready-to-merge

#3098 feat(citizen-scripting-lua): ClearTimeout function
  code/components/citizen-scripting-lua/include/LuaScriptRuntime.h
  code/components/citizen-scripting-lua/src/LuaScriptRuntime.cpp
  data/shared/citizen/scripting/lua/scheduler.lua
Labels: ready-to-merge, ScRT: Lua

#3101 fix(handling-loader): fix broken physics
  code/components/handling-loader-five/src/HandlingLoader.cpp
Labels: ready-to-merge

#3105 fix(gta-streaming-five): skeleton bone index bounds check
  code/components/gta-streaming-five/src/PatchSkeletonCrash.cpp
Labels: invalid, ready-to-merge

#3108 tweak(core/acl): give the creating resource the ability to modify the ACL for its own commands
  code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
Labels: invalid, ready-to-merge

#2780 feat(natives/vehicle): implement getter/setter for vehicle flags
  code/components/extra-natives-five/src/VehicleExtraNatives.cpp
  ext/native-decls/GetVehicleHasFlag.md
  ext/native-decls/SetVehicleFlag.md
Labels: invalid, ready-to-merge

#3062 feat(extra-natives/five): REGISTER_ROPE_DATA
  code/components/extra-natives-five/include/ropeManager.h
  code/components/extra-natives-five/src/NativeFixes.cpp
  code/components/extra-natives-five/src/RopeNatives.cpp
  data/client/citizen/common/data/gameconfig.xml
  ext/native-decls/RegisterRopeData.md
Labels: invalid, ready-to-merge

#3072 fix(input/five): DirectInput mouseDev unacquire
  code/components/rage-input-five/src/InputHook.cpp
Labels: invalid, ready-to-merge

#3076 fix(input/five): flush raw input mouse buttons on focus loss
  code/components/rage-input-five/src/InputHook.cpp
Labels: invalid, ready-to-merge

#3083 fix(nui/core): keep cursor clipping when no cursor is present
  code/components/nui-core/src/CefInput.cpp
Labels: invalid, ready-to-merge

#3113 feat(extra-natives-five): add DrawCorona native
  code/components/extra-natives-five/src/VfxNatives.cpp
  ext/native-decls/DrawCorona.md
Labels: invalid, ready-to-merge

#3133 fix(extra-natives-five): DrawCorona 16-byte vector alignment for SIMD instructions
  code/components/extra-natives-five/src/VfxNatives.cpp
Labels: bug, ready-to-merge

#3134 Revert "fix(handling-loader): fix broken physics"
  code/components/handling-loader-five/src/HandlingLoader.cpp
Labels: invalid, ready-to-merge

#3137 fix(server/gamestate): typo in freecam natives
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
Labels: invalid, ready-to-merge, RedM

#3167 🚗💨🚗💨🚗💨
  code/components/gta-core-five/src/CrashFixes.WheelFragLimits.cpp
Labels: invalid

#3157 fix(shared): include chrono to fix breakage caused by msvc-170
  code/client/shared/StdInc.h
Labels: ready-to-merge

#3165 tweak(server): shortened players.json privacy announcement link
  code/components/citizen-server-main/src/ServerInstance.cpp
Labels: ready-to-merge

#3058 Mumble tweaks/fixes
  code/components/extra-natives-five/src/NuiAudioSink.cpp
  code/components/gta-net-five/src/MumbleVoice.cpp
  code/components/voip-mumble/include/MumbleAudioSink.h
  code/components/voip-mumble/include/MumbleClient.h
  code/components/voip-mumble/include/MumbleClientImpl.h
  code/components/voip-mumble/include/MumbleClientState.h
  code/components/voip-mumble/src/MumbleAudioOutput.cpp
  code/components/voip-mumble/src/MumbleClient.cpp
  code/components/voip-mumble/src/MumbleClientState_Channel.cpp
  code/components/voip-mumble/src/MumbleClientState_User.cpp
  code/components/voip-mumble/src/MumbleVersionHandler.cpp
  ext/native-decls/MumbleSetServerAddress.md
Labels: invalid, ready-to-merge, RedM

#3044 feat(extra-natives/five): track switching
  code/components/extra-natives-five/src/TrackNatives.cpp
  ext/native-decls/GetClosestTrackNodes.md
  ext/native-decls/GetTrackNodeCoords.md
  ext/native-decls/GetTrackNodeCount.md
  ext/native-decls/RegisterTrackJunction.md
  ext/native-decls/RemoveTrackJunction.md
  ext/native-decls/SetTrackJunctionActive.md
Labels: invalid, ready-to-merge

#3129 feat(citizen-scripting-lua): Add os.createdir function
  code/components/citizen-scripting-lua/src/LuaOS.cpp
Labels: invalid, ready-to-merge, ScRT: Lua

#3176 fix(server): resMan init race
  code/components/citizen-server-impl/src/GetConfigurationMethod.cpp
Labels: invalid, ready-to-merge

#3170 feat(cfx-ui): update translations and price to mention portal
  ext/cfx-ui/src/assets/languages/locale-cs.json
  ext/cfx-ui/src/assets/languages/locale-da.json
  ext/cfx-ui/src/assets/languages/locale-de.json
  ext/cfx-ui/src/assets/languages/locale-en.json
  ext/cfx-ui/src/assets/languages/locale-fi.json
  ext/cfx-ui/src/assets/languages/locale-fr.json
  ext/cfx-ui/src/assets/languages/locale-hu.json
  ext/cfx-ui/src/assets/languages/locale-lt.json
  ext/cfx-ui/src/assets/languages/locale-nb_NO.json
  ext/cfx-ui/src/assets/languages/locale-nl.json
  ext/cfx-ui/src/assets/languages/locale-pl.json
  ext/cfx-ui/src/assets/languages/locale-pt.json
  ext/cfx-ui/src/assets/languages/locale-ro.json
  ext/cfx-ui/src/assets/languages/locale-ru.json
  ext/cfx-ui/src/assets/languages/locale-sv.json
  ext/cfx-ui/src/assets/languages/locale-tr.json
  ext/cfx-ui/src/assets/languages/locale-zh_Hans.json
  ext/cfx-ui/src/assets/languages/locale-zh_Hant.json
Labels: ready-to-merge

#3177 fix(native-decls): fix native hyperlinks
  ext/native-decls/GetGlobalPassengerMassMultiplier.md
  ext/native-decls/GetVehicleXmasSnowFactor.md
Labels: ready-to-merge

#3191 feat(five/streaming): expand train track array
  code/components/extra-natives-five/include/Train.h
  code/components/extra-natives-five/src/TrackNatives.cpp
  code/components/gta-streaming-five/src/PatchTrackLimits.cpp
Labels: invalid, ready-to-merge

#3193 tweak(extra-natives/five): track switching improvements
  code/components/extra-natives-five/src/TrackNatives.cpp
Labels: invalid, ready-to-merge
