Repository citizenfx/fivem, pull requests merged in 2025-03, with the labels that each got.

#3145 fix(core/rdr3): AMV hardcoded limit causing blinking
  code/components/gta-core-rdr3/src/PatchAMV.cpp
Labels: ready-to-merge, RedM

#3150 feat(extra-native-rdr3): `GET_MINIMAP_TYPE`
  code/components/extra-natives-rdr3/src/HudNatives.cpp
  ext/native-decls/GetMinimapType.md
Labels: ready-to-merge, RedM

#3174 tweak(gamestate/server): sanitize network synchronized scene
  code/components/citizen-server-impl/include/state/ServerGameState.h
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
  code/components/citizen-server-impl/src/state/ServerGameState_Scripting.cpp
  ext/native-decls/GetEntityRemoteSyncedScenesAllowed.md
  ext/native-decls/SetEntityRemoteSyncedScenesAllowed.md
Labels: invalid, ready-to-merge

#3183 fix(citizen-scripting-core): strict mode only for the client
  code/components/citizen-scripting-core/src/ResourceScriptFunctions.cpp
Labels: invalid, ready-to-merge

#3195 fix(gta-core-five): crash in out bound alternate variation cache
  code/components/gta-core-five/src/PedAlternateVariationCache.cpp
Labels: ready-to-merge

#3210 feat(extra-natives/five): visual settings getter native
  code/components/extra-natives-five/src/VisualSettingsNatives.cpp
  ext/native-decls/GetVisualSettingFloat.md
Labels: invalid, ready-to-merge

#2947 feat(gamestate/server): serverEntityCreated event
  code/components/citizen-server-impl/src/state/ServerGameState.cpp
Labels: ready-to-merge, triage

#3182 fix(gta-core-five): validate bounds collisions
  code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp
Labels: invalid, ready-to-merge

#3201 feat(v8/scripting): swap from msgpack-lite to msgpackr
  code/components/citizen-scripting-v8/src/V8ScriptRuntime.cpp
  data/shared/citizen/scripting/v8/bufferish.js
  data/shared/citizen/scripting/v8/main.js
  data/shared/citizen/scripting/v8/msgpack.d.ts
  data/shared/citizen/scripting/v8/msgpack.js
Labels: enhancement, invalid, ready-to-merge, ScRT: JS

#3220 tweak(github/ci): registry auth and lowercase image name
  .github/workflows/build_alpine_container.yml
  .github/workflows/ci/build_linux.sh
  .github/workflows/ci_build.yml
  .github/workflows/pr_opened.yml
Labels: ready-to-merge, triage

#3231 fix(scripting/node): load bufferish module in server scripts
  code/components/citizen-scripting-node/src/NodeScriptRuntime.cpp
Labels: ready-to-merge, ScRT: JS

#3186 fix(gta-streaming-five): sanitize ragdoll component based in attach bone
  code/components/gta-streaming-five/src/PatchSkeletonCrash.cpp
Labels: invalid

#3228 fix(scripting/node-v22): isolate data deallocation sequencing
  code/components/citizen-scripting-node/src/NodeScriptRuntime.cpp
Labels: invalid, ready-to-merge

#3229 fix(gta-core-rdr3): prevent player from being deleted when using `DELETE_/PED/ENTITY`
  code/components/gta-core-rdr3/src/EntityDeletionHacks.cpp
Labels: ready-to-merge, RedM

#3235 fix(v8/scripting): don't encode int64 to BigInt
  data/shared/citizen/scripting/v8/main.js
Labels: ready-to-merge, RedM, ScRT: JS

#3238 tweak(input/five): usabillity improvements
  code/components/citizen-game-main/src/FrontendNui.cpp
  code/components/glue/src/GtaNui.cpp
  code/components/nui-core/include/CefOverlay.h
  code/components/nui-core/src/CefInput.cpp
  code/components/rage-input-five/include/InputHook.h
  code/components/rage-input-five/src/InputHook.cpp
  code/components/rage-input-rdr3/include/InputHook.h
  code/components/rage-input-rdr3/src/InputHook.cpp
Labels: ready-to-merge, triage

#3246 fix(game/five): hotfix for disappearing hair on mask switch
  code/components/gta-core-five/src/PedAlternateVariationCache.cpp
Labels: ready-to-merge

#3251 fix(five/game): custom station sync from passenger
  code/components/gta-core-five/src/PatchVehicleRadioSync.cpp
Labels: ready-to-merge

#3253 fix(core-five): backport decorator crash mitigation
  code/components/gta-core-five/src/CrashFixes.cpp
Labels: ready-to-merge, triage

#3227 fix(extra-natives-rdr3): prevent local entities to be converted to networked objects
  code/components/extra-natives-rdr3/src/NativeFixes.cpp
Labels: ready-to-merge, RedM

#3254 fix(extra-natives-rdr3): fix net object rotation sync
  code/components/extra-natives-rdr3/src/NativeFixes.cpp
Labels: ready-to-merge, RedM

#3266 fix(core-five): CWeaponInfo crash mitigation
  code/components/gta-core-five/src/CrashFixes.VerifyCWeaponInfo.cpp
Labels: ready-to-merge, triage

#3127 fix(extra-natives-five): draw rect function offset
  code/components/extra-natives-five/src/Draw2dNatives.cpp
Labels: ready-to-merge

#3162 feat(server): add `GET_PLAYER_PEER_STATISTICS` to get useful peer stats
  code/components/citizen-server-impl/include/GameServerNet.h
  code/components/citizen-server-impl/src/GameServerNet.ENet.cpp
  code/components/citizen-server-impl/src/PlayerScriptFunctions.cpp
  ext/native-decls/GetPlayerPeerStatistics.md
  ext/native-decls/GetPlayerPing.md
Labels: ready-to-merge
